package api

import (
	"encoding/json"
	"fmt"
)

// HTTP_* error codes
const (
	HTTP_BAD_REQUEST      = 400
	HTTP_UNAUTHORIZED     = 401
	HTTP_FORBIDDEN        = 402
	HTTP_PAYMENT_REQUIRED = 403
	HTTP_NOT_FOUND        = 404
)

// APIError represents an error generated by the APIs
type APIError struct {
	Status  int
	Message string
}

func (a APIError) Error() string {
	return fmt.Sprintf("Error: %d - %s", a.Status, a.Message)
}

func (a APIError) JSON() []byte {
	data, _ := json.Marshal(a)
	return data
}

func NewAPIError(status int, message string) *APIError {
	return &APIError{
		Status:  status,
		Message: message,
	}
}
